<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EducationSystem.Domain\EducationSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstarctions\Identity\" />
    <Folder Include="Abstarctions\Logging\" />
    <Folder Include="Abstarctions\Common\" />
    <Folder Include="Abstarctions\UnitOfWork\" />
    <Folder Include="Abstarctions\Services\" />
    <Folder Include="Features\" />
    <Folder Include="Dtos\" />
    <Folder Include="Mapping\" />
    <Folder Include="Behaviours\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Common\" />
    <Folder Include="Specifications\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
