using EducationSystem.Domain.Entities.Common;

namespace EducationSystem.Domain.Entities;

public class ApplicationUser : BaseAuditableEntity
{
    /// --- Minimum Identity needs(mapped by OUR store, not IdentityDbContext) ---

    public string UserName { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string PasswordHash { get; set; } = string.Empty;   // was hidden inside IdentityUser
    public bool EmailConfirmed { get; set; }
    public string SecurityStamp { get; set; } = string.Empty;  // invalidates old reset tokens

    // NEW: optimistic-concurrency token.
    // Initialized with a random Guid, regenerated by the store on every update
    // — exactly how the built-in IdentityUser does it.
    public string ConcurrencyStamp { get; set; } = Guid.NewGuid().ToString();

    // ---- Your own properties (unchanged) ----
    public string FirstName { get; set; } = string.Empty;

    public string LastName { get; set; } = string.Empty;

    public string Address { get; set; } = string.Empty;
    public DateTime? DateOfBirth { get; set; }

    // CHANGED: enum replaced with a simple bool flag.
    // true = can log in, false = deactivated. Default true for new users.
    public bool IsActive { get; set; } = true;

    public string Role { get; set; }  // the user can have more than one role

    // ---- Relations ----

    // ---- Membership (NULLABLE ON PURPOSE — filled per the matrix) ----
    public Guid? OrganisationId { get; set; }

    public virtual Organisation? Organisation { get; set; }
    public Guid? SchoolId { get; set; }
    public virtual School? School { get; set; }
    public Guid? GradeId { get; set; }
    public virtual Grade? Grade { get; set; }
}